/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'AutoImports.d': typeof import('./auto-imports.d.ts')['default']
    Backtop: typeof import('./../components/Backtop/src/Backtop.vue')['default']
    ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    Editor: typeof import('./../components/Editor/src/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Form: typeof import('./../components/Form/src/Form.vue')['default']
    'Global.module': typeof import('./../styles/global.module.css')['default']
    'Global.module.css': typeof import('./../styles/global.module.css.map')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    IconSelect: typeof import('./../components/Icon/src/IconSelect.vue')['default']
    ImageViewer: typeof import('./../components/ImageViewer/src/ImageViewer.vue')['default']
    'Index.css': typeof import('./../styles/index.css.map')['default']
    InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSearch: typeof import('./../components/RouterSearch/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Styles: typeof import('./../styles/index.css')['default']
    Theme: typeof import('./../styles/theme.css')['default']
    'Theme.css': typeof import('./../styles/theme.css.map')['default']
    UploadFile: typeof import('./../components/UploadFile/src/UploadFile.vue')['default']
    UploadImg: typeof import('./../components/UploadFile/src/UploadImg.vue')['default']
    UploadImgs: typeof import('./../components/UploadFile/src/UploadImgs.vue')['default']
    UseValidator: typeof import('./../hooks/web/useValidator.ts')['default']
    Variables: typeof import('./../styles/variables.css')['default']
    'Variables.css': typeof import('./../styles/variables.css.map')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
